### ISSUE TITLE
We can't set if we want to open in app browser on iOS by Launch URL

### ISSUE THREAD

**Issue by CristianHourcadeBit** [OneSignal/onesignal-expo-plugin#47]
We were using the tool Launch URL sending a push, where that URL is a link to do a deep link to our application, but we realized that on iOS devices are opening a kind of modal in app, witch doesn't work with deep link.

So, I found this documentation: https://documentation.onesignal.com/docs/links#launch-url that seems we could change it if we want to open the browser or not, but that is for react native and not for expo applications, we can't modify the Info.plist

Is there some future update on this plugin to give us the possibility of change this? 

Thanks a lot

**Comment by rgomezp** [comment]
Howdy,
This is a great point. We will need to add a way to pass in custom list values. In the meantime, you should be able to modify it manually by going into the `ios` directory and opening up the workspace -- though it's not a good long-term option.

Thanks for your patience.

**Comment by jparksecurity** [comment]
I believe Android also has the same issue, right? Because we need to update `AndroidManifest.xml` as well.

**Comment by rgomezp** [comment]
Howdy,
This is now fixed for iOS on 4.3.6. Just make sure to call `setLaunchURLsInApp` before the `setAppId` call.

We will need to get back to you on the Android side.

**Comment by jparksecurity** [comment]
I updated expo plugin and `react-native-onesignal` to  4.3.6, but `setLaunchURLsInApp` still doesn't work.

Does it work for anyone?

**Comment by rgomezp** [comment]
@jparksecurity,
Did you make sure to call it before the `setAppId` call? (this will be resolved in a future native release but for now, it is the requirement to get it to work correctly)

**Comment by jparksecurity** [comment]
@rgomezp yes, I did. 

BTW I updated the onesignal doc to let a user know they should call it before `setAppId`

https://documentation.onesignal.com/docs/sdk-reference#setlaunchurlsinapp-method-ios

**Comment by rgomezp** [comment]
Howdy @jparksecurity ,
Sorry for the delay. Were you able to resolve this issue?

**Comment by jparksecurity** [comment]
Hello! @rgomezp 

Unfortunately, no. I wasn't able to fix it.

However,  I'm not sure if it is still happening because my team decided to move away from one signal, so I haven't tested it since the last comment.

**Comment by rgomezp** [comment]
Closing due to inactivity
